name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        env: # Or as an environment variable
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
          NODE_ENV: 'test'
        uses: cypress-io/github-action@v5.6.1 # use the explicit version number
        with:
          config: pageLoadTimeout=100000,baseUrl=${{ secrets.SERVER_URL }}
          browser: chrome
          build: npm run build
          start: NODE_ENV="test' npm start